import os

f = open((os.path.dirname(__file__) + '\\Monoisotopic mass table'), 'r')
temp = f.readlines()
f.close()

protein = "KMVGDHGKSPDYGFPEDFWNLAFIIVIECAEYRECMHQSQLMEMNDTFKHPCAWQVTVILFDMICRHEDRAHQKNLDRHDYEDTTKNTSEVVSNKYCKTNTIFSHWYLGVEDRCQTEDKYHPYWGEQVHLFFGWCPKFRSQGHINEDRNWEQAHMPITAEHTTIAQATPKMQGLIIITFDLQDMAFVKEQFSGFIIWKFDWDLQNLVDEMDEIRHYADHNVHWFDYHNGMRTEKWPTHQQEHRVGSNMYWPVYLSLCYIFDVMNEVHPQCHCCMRIEEQPLDMTNNMRMVRKATYLRAYRPIFENLTMTTTCGCPLAMIFYHDLIVCELDPKKLISDVPIGKRRFCEVPYAWMPCWCYMRTIIKGMGSGFIYYAQHMEVNVCKESEFWIAPQNMNQTSIPLLKDHDIINHANGGTTTTYPPCRQGWFRHHVDHWCPDTYAWTMTPNAMADVWTPSKMPWMQYIMELCITGHWPILQYRICCRGDIRGSQLHYPDTQRAEFHPDDRKEYWVNLLVQWYATIFRGLDNKVWEYVYCGNSTVVMRDLRTNAKIKKLNVIANMEAHQMQQQMFPFTPKFQRNSEWDRKMHYHILEQKRYAVEQIQIQLAICRDAAIMTQADMKKCECQTNGSVGSLRSHTGIDERPIMAVFKRTHWCFWPNIKLRTQCAGQTVPFDELNCWKWKWMRYPMKSDMRKWKMAWEWRWSECQFNTPWEEERNLLATFGLDKDHHKEWEVSNYIMIRLLGECENCIGFVFEMKWYRMRSFCYKYSPNGCHEDCTSTGQIWCKVGYWPWKDRGEYNWEIVRTWGINPWEMCTWHYQIPMKYAHGSEYTQPHMQYLKWWIKRKPEQMKVHIVIIDQLELI"

name = []
mass = []
for i in range(len(temp)):
    temp[i] = temp[i].split()
    name.append(temp[i][0])
    mass.append(float(temp[i][1]))

totalMass = 0
for p in protein:
    totalMass += mass[name.index(p)]
print("%.3f" % totalMass)