dna = "TCCTCGAGTTATCGTGTCCAAGACCGACTTAAATAGTGATAGCAGACAAGGACGTTATGGGCTTGCAATAAGCTTTTCCGCATCGACCCTCGCGCGTAGGCTGTGCCAAATCTCGATACGATTAGGTAGGAAGCCGCTGTCGCACTGGCATAGGTCTCCACGTCTCCTAATTTCTTCTATAGGCTAGGTATGGCTCTGGATAAGTTATCGATGTATTCCTGAGCCGCGTTTCTTCACGCATACCGCTTGAAAAGTATTTACCAAACGTGAACTTGGACAGAACAAGATGCCTATTTCACCAACGAGAGCGGAGGGTAGAAGAGACCCTAGTTCGCAATGCCCACCGATCGCTGCCAGGCAGGAAGGGACAAGAATTGAATAACCCATCGGAGCAGGGACGCAGATCGGGGTAGGCACGCGCGTAAGGTCGGGTAGACGTGATCCGCCCCGGTCAGAATCGCCAACCACTAGGCCTAGTTTGATTTACCGTAAAGTGGGTTTGGCAGTAATTAAGAGCTTCCCTAAAGAGCGCAAAATTGATTTCCATAGGTGGACACTTTAGGACGTAGAGCTAGTCGTCGTCGTCATAGTTCGGCTAAATGCTTCTCGTTTGTTTGAGTCAGAGGTGAGGAAAGCTGGCAGCAGTCACTTCTCAGTGAATGAAGCAGATGACCCGTCTCTGCCACACGTAGAAGCTTCAAAGCAGCCGCTGTGGCTCTTAGCTTTAACCCCGGGTGAGGAGGGCCACTCGTTGACCGGGATGCACCGCTCCAGCGGGACGGCGCGGCCTACCCGTTAAGAAAATTAGACCTGTGGATGGGAGTTCATGGGGTGTCGCGTTTCACGAAAGACTATGAAGCGCAAGGTTCTAAAACAGATACGGGCACGGCCAGGCTCGACAGCAAAAGGATAGACGAATTCTAGGCTTCGAATCCTCACTTTCTTAAATATTCATCTTA"
dna_c = ""

for c in dna:
    if c == 'A':
        dna_c += 'T'
    if c == 'C':
        dna_c += 'G'
    if c == 'G':
        dna_c += 'C'
    if c == 'T':
        dna_c += 'A'
print(dna_c[::-1])